In [2]:
import numpy as np

In [3]:
A = np.arange(0,8).reshape(4,2)
B = np.arange(10,18).reshape(2,4)

In [4]:
A

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [5]:
A

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [6]:
A + B   # farklı boyutlu matrisler toplanamaz

ValueError: operands could not be broadcast together with shapes (4,2) (2,4) 

In [7]:
A -B # farklı boyutlu matrisler çıkarılamaz

ValueError: operands could not be broadcast together with shapes (4,2) (2,4) 

In [8]:
A * B  # farklı boyutlu matrisler çarpılamaz (Matris çarpımı değil bu)

ValueError: operands could not be broadcast together with shapes (4,2) (2,4) 

In [9]:
np.matmul(A,B)  # matris çarpım operasyonu

array([[ 14,  15,  16,  17],
       [ 62,  67,  72,  77],
       [110, 119, 128, 137],
       [158, 171, 184, 197]])

In [10]:
A * 3  # skaler ile çarpım 

array([[ 0,  3],
       [ 6,  9],
       [12, 15],
       [18, 21]])

In [11]:
A / 3  # skaler ile bolum 

array([[0.        , 0.33333333],
       [0.66666667, 1.        ],
       [1.33333333, 1.66666667],
       [2.        , 2.33333333]])

In [12]:
A + 5 # skaler ile toplam 

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [13]:
A - 5  # skaler ile çıkarma 

array([[-5, -4],
       [-3, -2],
       [-1,  0],
       [ 1,  2]])

In [14]:
5 * A - B * 3   # skalerler ile temel işlemler yapılabilir 

ValueError: operands could not be broadcast together with shapes (4,2) (2,4) 

In [15]:
A

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [16]:
Z = np.arange(34,36).reshape(2,1)
Z

array([[34],
       [35]])

In [17]:
np.matmul(A,Z)  # 4x2 ve 2x1 matris çarpım sonucu 4x1 matristir

array([[ 35],
       [173],
       [311],
       [449]])

In [18]:
np.matmul(A,B)  # 4x2 matrisi ile 2x4 matrisi sonuç olarak 4x4 matris oluşturdu

array([[ 14,  15,  16,  17],
       [ 62,  67,  72,  77],
       [110, 119, 128, 137],
       [158, 171, 184, 197]])

In [19]:
np.matmul(B,A) # 2x4 matrisi ile 4x2 matrisi sonuç olarak 2x2 matris oluşturdu

array([[148, 194],
       [196, 258]])

In [20]:
np.matmul(A,B) == np.matmul(B,A)  # matris çarpımlarının yerleri değiştirilemez

/home/huseyin/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


False

In [21]:
A @ B  # @ işareti de matris çarpımı yapar

array([[ 14,  15,  16,  17],
       [ 62,  67,  72,  77],
       [110, 119, 128, 137],
       [158, 171, 184, 197]])

In [22]:
(A @ B) @ C == A @ (B @ C) # BU OZELLİK VAR  

NameError: name 'C' is not defined

In [23]:
I = np.eye((2))  # köşegenler 1 değeri alır
I

array([[1., 0.],
       [0., 1.]])

In [24]:
np. ones((3,3))  # köşegenler 0 değeri alır

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
V = np.arange(4).reshape(2,2)  
V

array([[0, 1],
       [2, 3]])

In [26]:
V * I == I * V # matris ile birim vektör çarpımı, matrisin kendisini verir

array([[ True,  True],
       [ True,  True]])

In [27]:
V @ I[:,0]

array([0., 2.])

In [28]:
Z = np.array([[2, 2, 1],
               [1, 3, 1],
               [1, 2, 2]])
np.linalg.inv(Z)  # matrisin tersini alma işlemi
# her matrisin tersi alınamaz. Kare matris olmak zorunda. 
# Her kare matrisin de tersi alınamaz.
# Tersi alınamayan matrislere singular matris denir

array([[ 0.8, -0.4, -0.2],
       [-0.2,  0.6, -0.2],
       [-0.2, -0.4,  0.8]])

In [29]:
np.matmul(Z, np.linalg.inv(Z))  
# matris ve matrisin tersinin çarpımı, birim matrisi verir

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.linalg.matrix_rank(Z) # matris rankı, matrisin rütbesini gösterir
# Bu 3x3lük Z matrisi, satır işlemleri sonucunda, herhangi bir satır sıfırlanamaz demek oluyor 

3

In [32]:
np.linalg.matrix_rank(A) # matris rankı, matrisin rütbesini gösterir
# Bu 3x3lük A matrisi, satır işlemleri sonucunda,  bir satır sıfırlandığını söyler
# Yani geriye sadece 2 satırlık matris kalacalmış, rank'tan bunu anladım. 

2

In [33]:
a = np.array([[1, 2], [3, 4], [5, 6]])
np.transpose(a)  # Transpozunu verir

array([[1, 3, 5],
       [2, 4, 6]])

In [34]:
a.transpose() # Transpozunu verir

array([[1, 3, 5],
       [2, 4, 6]])

In [35]:
a.T # Transpozunu verir

array([[1, 3, 5],
       [2, 4, 6]])

In [36]:
Z @ np.linalg.inv(Z)  

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.linalg.det(Z) 
# determinantı 0 olan matrisin tersi alınamaz. Singular matristir.

4.999999999999999

In [38]:
np.linalg.inv(Z) # matrisin tersi

array([[ 0.8, -0.4, -0.2],
       [-0.2,  0.6, -0.2],
       [-0.2, -0.4,  0.8]])

## MUTEAKIP DERS ICIN SUKRUNUN SORULARI
- toplamları 15den küçük eşit olan x ve y sayıları (reel sayılar) var.
- x ve y sıfırdan büyük eşit
- x -y min kaç
- x -y max kaç 